version: '3.6'
services:
  db:
    image: postgres:16.1-bullseye
    container_name: 'password-manager-db'
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: password-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    network_mode: host
    volumes:
      - /home/volumes/password_manager/db:/var/lib/postgresql/data