version: '3.6'
services:
  db:
    image: postgres:16.1-bullseye
    container_name: 'password-manager-db'
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: password-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - /home/volumes/db:/var/lib/postgresql/data