version: '3.6'
services:
  db:
    image: postgres:16.1-bullseye
    container_name: 'password-manager-db'
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: password-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    network_mode: host
    volumes:
      - /home/volumes/db:/var/lib/postgresql/data

  password-manager-api:
    image: 'password-manager-local'
    container_name: 'password-manager'
    build: ./
    command: bash -c 'alembic upgrade head && python run_server.py --port 5000'
    env_file: .env
    volumes:
      - '/home/volumes/password-manager/logs:/app/logs'
    network_mode: host
    depends_on:
      - db