"""empty message

Revision ID: 74bac5c2917f
Revises: 
Create Date: 2024-02-07 19:44:34.601877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74bac5c2917f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('us_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=8192), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=256), nullable=False),
    sa.Column('hash_algo', sa.String(length=10), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )

    op.create_table('us_user_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('inserted_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['us_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('us_user_token')
    op.drop_table('us_user')
    # ### end Alembic commands ###
